name: hw2_drq
channels:
  - defaults
dependencies:
  - python=3.7
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - "gym[atari]==0.19.0"
    - opencv-python
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core==0.11.3
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - sklearn
    - matplotlib
    - kornia
